class Custom_exception_db(Exception):
    pass
